legacy-c-impl/Makefile
legacy-c-impl/libremarkable/Makefile

I finally got around to building the legacy C system, and it seems to work. I did have to make some changes to the build system, which are described below.
The following changes were made:
- added optional CONFIG variable so I could use my local toolchain
- renamed CCFLAGS to more conventional CFLAGS (cosmetic)
- explicitely added "-static" option to CFLAGS 
- used Makefile $(RM) macro (cosmetic)
This PR will satisfy #5

Legacy C: slight modifications to build system.

---

src/framebuffer/common.rs
src/framebuffer/io.rs

I noticed that drawing images in Plato seemed a bit slow, it looks like this is partly due to the compiler not inlining pixel writing, resulting in a few function calls in every pixel! The changes I've attached here seem to satisfy the compiler.

Split out RGB conversion and encourage inlining

---

Cargo.toml
Makefile
docker-toolchain/.cargo/config
docker-toolchain/Dockerfile
src/lib.rs

This PR adds a docker image specification that can be used to build rust binaries for the reMarkable. It works on Linux (untested on OS X) and only requires Docker and make as dependencies.
Before this PR, a user compiling on ubuntu 16.04 would need to perform all the steps listed [here](https://github.com/canselcik/libremarkable/issues/5#issuecomment-377592830) except for starting a VM. On 18.04, I was unable to cross compile successfully at all due to glibc versioning, despite much effort. However, with this PR merged, any linux user with docker, make and reMarkable ssh set up can do:
```
git clone https://github.com/canselcik/libremarkable
cd libremarkable
make run-docker
```
and see the demo running on their device. They can also copy the make target for compiling their own programs. …

Docker toolchain

---

Cargo.toml
examples/demo.rs
examples/live.rs
src/appctx.rs
src/framebuffer/common.rs
src/framebuffer/draw.rs
src/framebuffer/io.rs
src/framebuffer/mod.rs
src/input/multitouch.rs
src/input/wacom.rs
src/lib.rs
src/ui_extensions/element.rs
src/ui_extensions/luaext.rs
tests/test_fb.rs

This PR implements use of `cgmath` ([github](https://github.com/rustgd/cgmath), [docs](https://docs.rs/cgmath)) in most places in the library (including the API) where floats or field/argument pairs have previously been used. An overview of the changes:
- use `cgmath` for all API coordinates, except `mxcfb_rect` and hardware translation layers
- add some utility methods to `cgmath` and use them
- change some numerical types, in an attempt to improve consistency and ergonomics:
- expose float arguments where it makes sense
- allow negative offsets in position, as this allows things to be drawn with an off-screen position that overlaps onto the screen.
- try to use the same number type width (e.g. u16 vs u32) in the same context unless there is an obvious reason not to
- to be honest, I'm …

Use cgmath for most coordinate representations

---

examples/demo.rs
examples/live.rs
src/appctx.rs
src/framebuffer/core.rs
src/framebuffer/draw.rs
src/framebuffer/io.rs
src/framebuffer/mod.rs
src/framebuffer/screeninfo.rs
src/ui_extensions/element.rs
src/ui_extensions/luaext.rs

This is a fairly find and replace change of all instances of isize/usize with i32/u32, except where we deal with memory directly. I discussed this possibility with @canselcik recently so I thought I'd put out a diff for further discussion.
There is exactly one place where I have left isize in the external API:
```
/// Reads the value at offset `ofst` from the mmapp'ed framebuffer region
fn read_offset(&self, ofst: isize) -> u8;
```
As this deals directly with a memory offset, I thought it best to leave it as is.
I also included a `cargo fmt`, but I can remove that if you prefer.

Standardise on u32 and i32 instead of usize/isize where possible.

---

examples/demo.rs
src/framebuffer/draw.rs
src/framebuffer/graphics.rs
src/framebuffer/mod.rs
src/input/wacom.rs

Summary:
- add polygon rasterisation
- base bezier drawing on rasterisation
- add bezier method with width interpolation
- parameterise bezier drawing by sample count
- refactor graphics functions into separate package with testability
- change circle filling to use plain squares comparison
- return floats for pen positions
- smooth out pen drawing by using sample midpoints
- add diamond touch mode for demonstration of vector drawing
- add -- and ++ buttons for quick brush sizing (+/-10)
Points of note:
- This does not fix the text drawing issue introduced in the previous PR. That will require a separate investigation.
- This is a breaking API change, but less so than the cgmath change.
- By making the `graphics` module non-public, functions can be freely moved into it as necessary …

Graphics rendering improvements

---

src/battery.rs

The path to the battery information changed with the latest update (1.8).
This works (I just tested it), but this would break the build for libremarkables < 1.8, so I open the PR to discuss the best solution.
Possible solutions that came to my mind:
- a) Notice it in the README as a breaking change
- b) Check 1.7 path and if not available use the 1.8 path
Bests

Closes #24

---

README.md

ARM toolchains on recent systems are often build with a newer Glibc than
the reMarkable has installed. This leads to runtime errors.
If the official toolchain from reMarkable is used, that's not an issue.
This commit updates the README with instructions on how to use this toolchain.
The link to the AUR package was removed as the most recent version also depends
on a too recent Glibc.
I've tested those steps on Debian testing.
Fixes #29.

Update README to address compilation on recent systems

---

src/framebuffer/core.rs

When an application that is using libremarkable is started right after
booting the device, it doesn't display anything.
In order to fix this problem, `pixclock` is set to 6250. This will result
in the expected flashing of the display as when starting other applications.
Though the rendering will be garbled/corrupted.
In order to fix that, the fix screen info needs to be read after the
var screen info was set. The fix screen info returns the number of lines
based on the rotation of the screen. Right after starting the reMarkable
the screen is set to landscape mode. libremarkable sets it to portrait mode
via the var screen info, which changes the line length of the fix screen info.
I also adjusted the `xres` and `yres` in the code to reflect the values
after the `ioctl` was successfully …

Fix initial rendering

---

README.md

Some time ago, a new toolchain came out on [remarkable.engineering](https://remarkable.engineering/) that primarily had some QT updates that was used in an official update.
Even though this probably doesn't affect this rust project, sticking with the newer toolchain will probably reduce confusion for newer developers that haven't encountered poky before.
I used this toolchain for testing the demo and live examples (my screenshot tool of choice) and had no problems with it.

Update instructions to oecore toolchain instead of poky

---

Cargo.toml
examples/demo.rs
examples/live.rs
examples/spy.rs
src/appctx.rs
src/framebuffer/common.rs
src/framebuffer/core.rs
src/framebuffer/draw.rs
src/framebuffer/graphics.rs
src/framebuffer/io.rs
src/framebuffer/mod.rs
src/framebuffer/mxcfb.rs
src/framebuffer/refresh.rs
src/framebuffer/storage.rs
src/input/ecodes.rs
src/input/ev.rs
src/input/gpio.rs
src/input/mod.rs
src/input/multitouch.rs
src/input/wacom.rs
src/lib.rs
src/ui_extensions/element.rs
src/ui_extensions/luaext.rs

This is a PR that updates the codebase to Rust 2018 editions idioms. It also does a few more cleanups I thought make sense. I wanted to make other change to libremarkable, but I'm so used to Rust 2018 edition codebases, hence this PR.
@canselcik please see this as a proposal. I intentionally tried to keep the commits small and self contained, so that you can decide if there are changes you don't like. I'm happy to rebase things and removing stuff or making other changes.
One issue is that `ioctl-gen` cannot be used with normal imports. I've created https://github.com/quadrupleslap-old/ioctl-gen/pull/1 to fix this. For now I've put my branch into Cargo.toml, that of course needs to be resolved before merging.
The demo application still works on my device.

Use Rust 2018 edition idioms

---

.github/workflows/build.yml

Provide basic CI. It makes sure that the code is formatted according
to rustfmt and that there are no clippy warnings.
Cross-compilation support could be added, but I thought as a starts, basic CI is better than none.

chore: add basic CI

---

src/input/ev.rs

When paused (SIGSTOP) and resumed (SIGCONT) in remux, the ev eventloop would panic on the replaced unwrap() call, which led to missing input events.
This was brought up in issue https://github.com/LinusCDE/retris/issues/1. See there for more information.

Fix thread panic when resumed in remux

---

Cargo.toml
examples/input.rs
src/device.rs
src/framebuffer/common.rs
src/input/ev.rs
src/input/gpio.rs
src/input/mod.rs
src/input/multitouch.rs
src/input/rotate.rs
src/input/scan.rs
src/input/wacom.rs
src/lib.rs

This PR makes the input system compatible with the rM2.
The the rM2 the event files have changed their order. There are different ways of getting the correct file. I used @raisjn's [aproach](https://gist.github.com/raisjn/01b16286dcc4461a6643f40f8f553966) by checking the capabilities of each device (see [this issue](https://github.com/Eeems/oxide/issues/48) for more).
This basicially opens every `/dev/input/event*` file once before the first device is accessed to build a HashMap correlating all `InputDevice`s event file paths.
This should also keep working when a rM3 gets released.
One downside I found with this though is, that the Multitouch device on the rM1 has some serious delay when opening it.
```
reMarkable: /home/root/ ./input # Modified to measure detection times
Duration …
```

reMarkable 2 input support

---

src/device.rs
src/input/multitouch.rs
src/input/scan.rs
src/input/wacom.rs

Hi,
this PR finally adds the correct input mapping for Multitouch. Seems there was no way around adding inversion of axis. @raisjnn confirmed that this mapping (the input example) works on the rM2 now.
After this, the rM 2 should fully work when used together with [the shim](https://github.com/ddvk/remarkable2-framebuffer/).

Fix wrong MT input mapping for the rM 2

---

src/battery.rs
src/device.rs

Commit message: This was not tested. Though by viewing the file tree of /sys provided by @torwag [here](https://github.com/Eeems/oxide/issues/48#issue698181952) (file tree.txt line 3166) it seems that all methods are supported.
I didn't test whether this actually works on a rM 2 as I don't own that device. I'm confident though that it should work. I added the compiled demo binary that also reports that battery data. Please test whether it displays Charging/Discharging and the percentage on the reMarkable 2.
---
- [demo.tar.gz](https://github.com/canselcik/libremarkable/files/5740678/demo.tar.gz)

Add support for the rM2 battery

---

.github/workflows/build.yml
Cargo.toml
Makefile
examples/swtfb_sysv_spy.rs
src/appctx.rs
src/device.rs
src/framebuffer/core.rs
src/framebuffer/mod.rs
src/framebuffer/mxcfb.rs
src/framebuffer/refresh.rs
src/framebuffer/swtfb_client.rs
src/framebuffer/swtfb_ipc.rs

See #76 . This should also enable musl builds and hence solve that problem.
Code should be semi clean. As mentioned in #76 we might want to change "Core" and "Swtfb" into seperate backends (also todo when doing breaking changes: use `AsRef<std::path::Path>` in `from_path`).
Testing if wanted:
- Musleabihf build should work for demo example
- Demo example with libc should run with AND without shim (e.g. LD_PRELOAD=... or rm2fb-shim).
Artifacts built with `cross build --target=armv7-unknown-linux-gnueabihf --release --example demo` and `cross build --target=armv7-unknown-linux-musleabihf --release --example demo` : [demos.tar.gz](https://github.com/canselcik/libremarkable/files/7532384/demos.tar.gz)
New:
- `framebuffer::swtfb_client`
- `examples/swftb_sysv_spy.rs` as dylib (for LD_PRELOAD) …

Add built-in swtfb client and enable musl builds on rM 2

---

src/framebuffer/common.rs

This is a minor fix that allows to Copy and Clone all types in `src/framebuffer/common.rs`. More a minor thing to improve usability for some cases.
I originally stumbled upon this when doing [doomarkable](https://github.com/LinusCDE/doomarkable). Wanted to specify the waveform depending on the device and later reuse it depending on the model in a render loop. Problem was that the variable in loop wouldn't work, since the parameter is owned and rusts ownership wouldn't permit me to give ownership repeatedly away in a loop (duh).
Wouldn't be a problem if the waveform mode could be cloned or such, but this wasn't derive. So I would basically need to create my own clone, remember it otherwise (basically serializing to a different type (e.g. and int) deserializing it again every time). My …

Impl Copy, Clone for all types in common.rs

---

examples/screenshot.rs

A quick screenshot script; it writes the screen contents as a PNG to the given path, or to stdout if no path is given.
This is a small amount of code, but seemed generally useful enough -- and a simple enough usage of the library -- to be worth contributing. But if y'all disagree I don't feel super strongly about it.

Add a screenshot utility

---

examples/swtfb_sysv_spy.rs
src/framebuffer/swtfb_client.rs

Found this, when using this implementation for plato:
The cause was that `sem_timedwait` was called on `sem_open`'s result `SEM_FAILED`. That call failed with `errno == 22` ("Invalid value"). Seems that the rust code called the code too fast and and probably made more likely by more frequent wait()'s in plato due to the ui system. Plato uses a bus system for almost everything, so afaik, calls should never be happen in parallel.
The implemenation was 1:1 like the reference implementation. While this didn't ever happen on the official rm2fb client, the cause might still be interesting to investigate and could possibly hint to a problem in the original impl. (cc @raisjn)
Added a way to do several attempts with delays which should provide a good enough workaround. Also turned later occuring …

Fix rare segfault on wait_for_update

---

examples/basic_draw.rs
examples/demo.rs
src/appctx.rs

The old model was hard to use and not very Rusty, so I decided to make it work a bit more like winit.
Also comes with a new demo showcasing how easy it is to use the new event loop to build a simple program.

New event loop usage

---

src/framebuffer/swtfb_client.rs

Collecting problems found so far. Should in the end fix the issue found in #88. This will close #88.

Fix: Built-in rm2fb client corrupts the server state

---

src/appctx.rs
src/framebuffer/core.rs
src/framebuffer/draw.rs
src/framebuffer/io.rs
src/framebuffer/mod.rs
src/framebuffer/refresh.rs
src/ui_extensions/luaext.rs

This means you won't pay the cost of
- font storage in the binary
- up-front font parsing at runtime
- storage of the parsed structures at runtime
if you don't use the built-in font drawing code.

make Roboto optional

---

examples/live.rs
src/appctx.rs
src/framebuffer/core.rs
src/framebuffer/mod.rs
src/framebuffer/refresh.rs

This rearranges the public API slightly to be more explicit: the user can now call `Framebuffer::new` explicitly, or `::classic` or `::rm2fb` to pick a specific backend.
Internally, this switches to using an enum for the old/new backend. This should be about as efficient to the old option-based interface, but moving the file descriptor used for ioctls into the enum makes certain types of errors less likely. My actual motive was to try and add a noop backend to allow for easier testing, but I'll leave that for a followup.
Haven't tested this properly yet, so marking as draft. Interested in thoughts if anyone has them!

Framebuffer interface

---

src/framebuffer/common.rs

The old algorithm has some unpleasant tinting. Native components `[0xFF, 0xFF]` don't result in rgb components `[0xFF, 0xFF, 0xFF]` but rather `[0xF8, 0xFC, 0xF8]`. This affects screenshots for example.
Obviously some fudging is needed in order to come up with the "extra resolution" in rgb8 to make the mins and maxes match up. Roundtripping from 565 -> 888 -> 565 is still a thing. And now it's a part of the test suite, which verifies that every rgb565 value can be roundtripped to rgb8 and back. And that rgb565 -> rgb8 conversions behave properly.
The new conversion routines still only use integer arithmetic. I haven't benchmarked them but they should actually be slightly faster than the old routines.
Note that I tested these on my desktop machine which required #92 in order to get …

Make rgb565 conversion algorithms a bit better

---

src/framebuffer/swtfb_client.rs

Fixes #98.
@matteodelabre - does this look like the proper fix, or is there more to do?

msgsz should measure only the message contents

---

src/framebuffer/core.rs

I need this variable to be public, since you can't rotate the framebuffer in hardware otherwise (rm 1 only). Thought I could get away with a new instance, but since the new instance re initializes my changed data (and resets the rotation value), it wouldn't work that way.
On the rM 2, I know do this in software (was disabled there until now) but for the rM 1 I prefer to let the hardware do the pixel transformation.
Another solution to this would be to implement [this](https://github.com/LinusCDE/plato/blob/09fd60ef9f45ee3621793bc7e7b8bbbe5a687dea/src/framebuffer/remarkable.rs#L381) as part of a new function to update the fix_screen_info. But I recon nobody except me will ever need this, and it might sound weird to "update fixed info". But I have no problems doing this instead if …

Make framebuffer_update public

---

.gitignore
README.md
gen_cargo_config.py

This commit adds a python script to generate the correct .cargo/config for the installed toolchain. All path are extracted from the environment variables after sourcing the toolchain's environment file.

added script to generate .cargo/config from toolchain environment 💪

---

.gitmodules

Due to recent [changes in GitHub’s supported protocols](https://github.blog/2021-09-01-improving-git-protocol-security-github/), the fetching of submodules of this repository is failing. This also causes [folly](https://github.com/bkirwi/folly)’s build to fail, since for some reason the submodules are fetched as part of the build (@bkirwi).
This patch simply updates the submodule’s URL to use https:// instead of git://.

Fix submodule URL for Freetype

---

src/input/wacom.rs

This should fix a weird edge-case bug in the event handling code. (Thanks to `okeh` on the discord for finding this issue and helping me debug.)
I've included the commit-message description below, but let me know if anything's not clear. (Or if you know what the "interesting behaviour" in the `ecodes::ABS_DISTANCE` handler is!)
---
Previously, the wacom code would emit WacomEvent::Hover iff the last event seen was ToolPen. This has the wrong behaviour when the pen is leaving the screen, since a Touch event gets emitted as the pen lifts but another ToolPen won't be emitted until the pen is no longer near the screen at all. Instead, we use the current touch state to decide if we're hovering or
not.
So why wasn't this always broken? In the ABS_DIST code farther down in the file, it would …

Switch to using touch state instead of most recent event

---

examples/demo.rs
src/framebuffer/common.rs
src/input/mod.rs
src/ui_extensions/element.rs

This fixes the failing clippy check in #107 and remove a warning when building the example `demo`.
As with that issue, will merge this in about a day if nobody is against it (cc @bkirwi, @fenollp).

Fix warnings and satisfy clippy

---

Cargo.toml

This should fix issue #106 by capping the version of evdev used for now.
I also tested with the newer minor version (0.12.0) and it had the same issue as well.

Prevent usage newer evdev than 0.11.3 due to compilation error for armv7

---

README.md

The wiki is no longer loading, but luckily there are recent archive.org crawls of the site that can be used.

Update wiki links to archive.org

---

.github/workflows/build.yml
Cargo.toml
examples/demo.rs
examples/live.rs
examples/screenshot.rs
examples/swtfb_sysv_spy.rs
src/appctx.rs
src/framebuffer/common.rs
src/framebuffer/draw.rs
src/framebuffer/swtfb_client.rs
src/input/ev.rs
src/input/multitouch.rs
src/input/wacom.rs

Note: some audited deps are not simple to upgrade (and weren't). This needs further work:
```
λ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 561 security advisories (from /home/pete/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (134 crate dependencies)
Crate:     rustc-serialize
Version:   0.3.24
Title:     Stack overflow in rustc_serialize when parsing deeply nested JSON
Date:      2022-01-01
ID:        RUSTSEC-2022-0004
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0004
Solution:  No fixed upgrade is available!
Dependency tree:
rustc-serialize 0.3.24
├── num-rational 0.1.42
│   └── num 0.1.42
│       └── stopwatch 0.0.7
│           └── libremarkable 0.6.0
├── num-complex 0.1.43
│   └── num …
```

Fix clippy warnings + uprade some audited deps 

---

examples/live.rs

I usually used a "livepng" version where I replaced the "JpegEncoder" with an "PngEncoder" since the images where usually smaller and lossless for my usecases (usually screenshots for READMEs in my projects).
Started this out with the intend to add png support alongside jpeg. Since we're using a webserver, I also decided to add a minimal html page to allow users to choose what format to use. Also checked that it renders okay on smartphones.
You can also now see the duration of the encoding in the console.

Add more image formats to "live" example and a html selection page

---

Cargo.toml
src/appctx.rs
src/ui_extensions/element.rs

- move env_logger to dev-dependencies (was only used in the examples)
- move image functions behind existing feature flag
I bumped the version to 0.7.0 as this could be a breaking change for someone having appctx but not image enabled.
The motivation was to flatten the dependency tree, reduce build time and reduce target folder size.

reduce required dependencies

---

examples/demo.rs

Unanticipated inputs from the Wacom Pen will cause the code to reach unreachable causing the entire app to crash. This includes any side buttons on 3rd party pens

Fixed Crashing Due To Unknown Pen Inputs

---

src/framebuffer/draw.rs

potentially, add background (this is for foreground color)
See issue #122

More intuitive color use for the draw_text function

---

src/framebuffer/core.rs
src/framebuffer/draw.rs

First: when we added an env var recently to allow forcing a fallback to the rm1 framebuffer interface, we were still using the rm2 path. This path does exist, but attempting ioctls on it will fail. Fixed by specifying the old path when setting the env var.
Second: this recent font rendering change broke the demo app! I didn't look into it, but for now let's just get main back in a good state. It's a small diff.

Fix a couple recent regressions
